# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dmitry Ryadnenko
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about Android, Kotlin and RxJava development
baseurl: "/kotlin-blog" # the subpath of your site, e.g. /blog
url: "https://rongi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: DmitryRyadnenko
github_username:  rongi
author: Dmitry Ryadnenko

social:
  twitter: DmitryRyadnenko
  facebook: DmitryRd
  github:  rongi
  rss: rss
  # googleplus: +jekyll
  # dribbble: jekyll
  # flickr: jekyll
  # instagram: jekyll
  # linkedin: jekyll
  # pinterest: jekyll
  # stackoverflow: 12345/jekyll
  # youtube: jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock

# Google services
google_analytics: UA-101153501-1

disqus:
  shortname: rongi-github-io-kotlin-blog
